### ISSUE TITLE
Stopped working after 3 days

### ISSUE THREAD

**Issue by arandomdeadbear** [Erisa/RoundedTB#297]
It was running good but idk why for some reason, when I turned my pc on today it didnt load on startup, tho it was working just fine yesterday, and i tried to run  the exe file manually but it did nothing, it didnt open. i re downloaded the files still nothing

**Comment by notRyuk** [comment]
From where have you installed from??

Try installing from *windows store*. It happened same for me when I have a version installed and then uninstall everything and try removing the temp files.

**Comment by dev-xero** [comment]
Make sure you've enabled run at startup. 
<img width="212" alt="image" src="https://github.com/Erisa/RoundedTB/assets/70282966/036f0b65-97e1-4385-ae93-0c7c2004b411">

**Comment by ohrly** [comment]
Maybe try to delete the `%localappdata%/rtb.json` and `%localappdata%/rtb.log`, that did revive the app for me.
I got this error in Event Viewer Application Log:
```
Application: RoundedTB.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at RoundedTB.MainWindow..ctor()
```

**Comment by arandomdeadbear** [comment]
> From where have you installed from??
> 
> Try installing from _windows store_. It happened same for me when I have a version installed and then uninstall everything and try removing the temp files.

Thanks it worked after installing from MS store, I downloaded it from the GitHub release.
